[2024-07-09 23:25:01,567] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: create_layers_in_snowflake.create_seeds manual__2024-07-09T23:25:00.823284+00:00 [queued]>
[2024-07-09 23:25:01,577] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: create_layers_in_snowflake.create_seeds manual__2024-07-09T23:25:00.823284+00:00 [queued]>
[2024-07-09 23:25:01,578] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-07-09 23:25:01,578] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-07-09 23:25:01,578] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-07-09 23:25:01,592] {taskinstance.py:1377} INFO - Executing <Task(DockerOperator): create_seeds> on 2024-07-09 23:25:00.823284+00:00
[2024-07-09 23:25:01,595] {standard_task_runner.py:52} INFO - Started process 147 to run task
[2024-07-09 23:25:01,599] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_layers_in_snowflake', 'create_seeds', 'manual__2024-07-09T23:25:00.823284+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/create_layers.py', '--cfg-path', '/tmp/tmpc869q5a0', '--error-file', '/tmp/tmpnhi6kc21']
[2024-07-09 23:25:01,599] {standard_task_runner.py:80} INFO - Job 9: Subtask create_seeds
[2024-07-09 23:25:01,653] {task_command.py:369} INFO - Running <TaskInstance: create_layers_in_snowflake.create_seeds manual__2024-07-09T23:25:00.823284+00:00 [running]> on host a22086a40575
[2024-07-09 23:25:01,727] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_layers_in_snowflake
AIRFLOW_CTX_TASK_ID=create_seeds
AIRFLOW_CTX_EXECUTION_DATE=2024-07-09T23:25:00.823284+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-09T23:25:00.823284+00:00
[2024-07-09 23:25:01,748] {docker.py:247} INFO - Starting docker container from image custom_dbt_image
[2024-07-09 23:25:01,757] {docker.py:258} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-07-09 23:25:01,878] {docker.py:308} INFO - thisisatest
[2024-07-09 23:25:01,958] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=create_layers_in_snowflake, task_id=create_seeds, execution_date=20240709T232500, start_date=20240709T232501, end_date=20240709T232501
[2024-07-09 23:25:01,982] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-07-09 23:25:02,017] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
