[2024-07-10 16:42:26,144] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_questions.bash1 manual__2024-07-10T16:42:25.167819+00:00 [queued]>
[2024-07-10 16:42:26,155] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_questions.bash1 manual__2024-07-10T16:42:25.167819+00:00 [queued]>
[2024-07-10 16:42:26,156] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 16:42:26,156] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-07-10 16:42:26,156] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 16:42:26,172] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): bash1> on 2024-07-10 16:42:25.167819+00:00
[2024-07-10 16:42:26,176] {standard_task_runner.py:52} INFO - Started process 4488 to run task
[2024-07-10 16:42:26,180] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_questions', 'bash1', 'manual__2024-07-10T16:42:25.167819+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/test_questions.py', '--cfg-path', '/tmp/tmpkfab4082', '--error-file', '/tmp/tmphbxvh_5i']
[2024-07-10 16:42:26,181] {standard_task_runner.py:80} INFO - Job 8: Subtask bash1
[2024-07-10 16:42:26,243] {task_command.py:369} INFO - Running <TaskInstance: test_questions.bash1 manual__2024-07-10T16:42:25.167819+00:00 [running]> on host c8efd281e0f4
[2024-07-10 16:42:26,317] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_questions
AIRFLOW_CTX_TASK_ID=bash1
AIRFLOW_CTX_EXECUTION_DATE=2024-07-10T16:42:25.167819+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-10T16:42:25.167819+00:00
[2024-07-10 16:42:26,318] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-07-10 16:42:26,319] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbtlearn && dbt run --select test_interview']
[2024-07-10 16:42:26,327] {subprocess.py:85} INFO - Output:
[2024-07-10 16:42:29,152] {subprocess.py:92} INFO - [0m16:42:29  Running with dbt=1.5.0
[2024-07-10 16:42:30,227] {subprocess.py:92} INFO - [0m16:42:30  Encountered an error:
[2024-07-10 16:42:30,227] {subprocess.py:92} INFO - Compilation Error
[2024-07-10 16:42:30,228] {subprocess.py:92} INFO -   Model 'model.dbtlearn.test_interview' (models/test_interview/test_interview.sql) depends on a source named 'test-interview.DEV.FULL_MOON_DATES' which was not found
[2024-07-10 16:42:30,662] {subprocess.py:96} INFO - Command exited with return code 2
[2024-07-10 16:42:30,680] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-07-10 16:42:30,685] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=test_questions, task_id=bash1, execution_date=20240710T164225, start_date=20240710T164226, end_date=20240710T164230
[2024-07-10 16:42:30,697] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task bash1 (Bash command failed. The command returned a non-zero exit code 2.; 4488)
[2024-07-10 16:42:30,725] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-10 16:42:30,766] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
