[2024-07-10 14:02:21,968] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: create_layers_in_snowflake.create_target_layer manual__2024-07-10T14:02:11.944294+00:00 [queued]>
[2024-07-10 14:02:21,978] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: create_layers_in_snowflake.create_target_layer manual__2024-07-10T14:02:11.944294+00:00 [queued]>
[2024-07-10 14:02:21,978] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 14:02:21,979] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-07-10 14:02:21,979] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 14:02:21,992] {taskinstance.py:1377} INFO - Executing <Task(DockerOperator): create_target_layer> on 2024-07-10 14:02:11.944294+00:00
[2024-07-10 14:02:21,996] {standard_task_runner.py:52} INFO - Started process 1081 to run task
[2024-07-10 14:02:21,999] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_layers_in_snowflake', 'create_target_layer', 'manual__2024-07-10T14:02:11.944294+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/create_layers.py', '--cfg-path', '/tmp/tmpefbqa5rh', '--error-file', '/tmp/tmpd2vmdr90']
[2024-07-10 14:02:22,000] {standard_task_runner.py:80} INFO - Job 18: Subtask create_target_layer
[2024-07-10 14:02:22,055] {task_command.py:369} INFO - Running <TaskInstance: create_layers_in_snowflake.create_target_layer manual__2024-07-10T14:02:11.944294+00:00 [running]> on host bc9f9d1e47b7
[2024-07-10 14:02:22,130] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_layers_in_snowflake
AIRFLOW_CTX_TASK_ID=create_target_layer
AIRFLOW_CTX_EXECUTION_DATE=2024-07-10T14:02:11.944294+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-10T14:02:11.944294+00:00
[2024-07-10 14:02:22,154] {docker.py:247} INFO - Starting docker container from image custom_dbt_image
[2024-07-10 14:02:24,000] {docker.py:308} INFO - Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.

Error: Invalid value for '--profiles-dir': Path '/root/.dbt' does not exist.
[2024-07-10 14:02:24,150] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 387, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 266, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 313, in _run_image_with_mounts
    raise AirflowException(f'Docker container failed: {repr(result)} lines {joined_log_lines}')
airflow.exceptions.AirflowException: Docker container failed: {'StatusCode': 2} lines Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.

Error: Invalid value for '--profiles-dir': Path '/root/.dbt' does not exist.
[2024-07-10 14:02:24,154] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=create_layers_in_snowflake, task_id=create_target_layer, execution_date=20240710T140211, start_date=20240710T140221, end_date=20240710T140224
[2024-07-10 14:02:24,168] {standard_task_runner.py:97} ERROR - Failed to execute job 18 for task create_target_layer (Docker container failed: {'StatusCode': 2} lines Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.

Error: Invalid value for '--profiles-dir': Path '/root/.dbt' does not exist.; 1081)
[2024-07-10 14:02:24,192] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-10 14:02:24,242] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
