[2024-07-10 16:31:25,910] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_questions.bash1 manual__2024-07-10T16:31:25.094777+00:00 [queued]>
[2024-07-10 16:31:25,925] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_questions.bash1 manual__2024-07-10T16:31:25.094777+00:00 [queued]>
[2024-07-10 16:31:25,926] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 16:31:25,926] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-07-10 16:31:25,927] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 16:31:25,944] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): bash1> on 2024-07-10 16:31:25.094777+00:00
[2024-07-10 16:31:25,948] {standard_task_runner.py:52} INFO - Started process 3844 to run task
[2024-07-10 16:31:25,952] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_questions', 'bash1', 'manual__2024-07-10T16:31:25.094777+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/test_questions.py', '--cfg-path', '/tmp/tmpekrdqtfh', '--error-file', '/tmp/tmpsteov2xp']
[2024-07-10 16:31:25,953] {standard_task_runner.py:80} INFO - Job 6: Subtask bash1
[2024-07-10 16:31:26,033] {task_command.py:369} INFO - Running <TaskInstance: test_questions.bash1 manual__2024-07-10T16:31:25.094777+00:00 [running]> on host c8efd281e0f4
[2024-07-10 16:31:26,119] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_questions
AIRFLOW_CTX_TASK_ID=bash1
AIRFLOW_CTX_EXECUTION_DATE=2024-07-10T16:31:25.094777+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-10T16:31:25.094777+00:00
[2024-07-10 16:31:26,120] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-07-10 16:31:26,121] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbtlearn && dbt run --select test_interview']
[2024-07-10 16:31:26,130] {subprocess.py:85} INFO - Output:
[2024-07-10 16:31:26,132] {subprocess.py:92} INFO - bash: line 1: dbt: command not found
[2024-07-10 16:31:26,133] {subprocess.py:96} INFO - Command exited with return code 127
[2024-07-10 16:31:26,149] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-10 16:31:26,154] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=test_questions, task_id=bash1, execution_date=20240710T163125, start_date=20240710T163125, end_date=20240710T163126
[2024-07-10 16:31:26,166] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task bash1 (Bash command failed. The command returned a non-zero exit code 127.; 3844)
[2024-07-10 16:31:26,175] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-10 16:31:26,221] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
