[2024-07-09 23:23:39,431] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: create_layers_in_snowflake.create_seeds manual__2024-07-09T23:23:38.658191+00:00 [queued]>
[2024-07-09 23:23:39,441] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: create_layers_in_snowflake.create_seeds manual__2024-07-09T23:23:38.658191+00:00 [queued]>
[2024-07-09 23:23:39,441] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-07-09 23:23:39,441] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-07-09 23:23:39,442] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-07-09 23:23:39,460] {taskinstance.py:1377} INFO - Executing <Task(DockerOperator): create_seeds> on 2024-07-09 23:23:38.658191+00:00
[2024-07-09 23:23:39,464] {standard_task_runner.py:52} INFO - Started process 82 to run task
[2024-07-09 23:23:39,469] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_layers_in_snowflake', 'create_seeds', 'manual__2024-07-09T23:23:38.658191+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/create_layers.py', '--cfg-path', '/tmp/tmpslj6zgvh', '--error-file', '/tmp/tmp68307a2n']
[2024-07-09 23:23:39,470] {standard_task_runner.py:80} INFO - Job 8: Subtask create_seeds
[2024-07-09 23:23:39,546] {task_command.py:369} INFO - Running <TaskInstance: create_layers_in_snowflake.create_seeds manual__2024-07-09T23:23:38.658191+00:00 [running]> on host a22086a40575
[2024-07-09 23:23:39,618] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_layers_in_snowflake
AIRFLOW_CTX_TASK_ID=create_seeds
AIRFLOW_CTX_EXECUTION_DATE=2024-07-09T23:23:38.658191+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-09T23:23:38.658191+00:00
[2024-07-09 23:23:39,638] {docker.py:247} INFO - Starting docker container from image custom_dbt_image
[2024-07-09 23:23:39,647] {docker.py:258} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-07-09 23:23:39,782] {docker.py:308} INFO - this
[2024-07-09 23:23:39,853] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=create_layers_in_snowflake, task_id=create_seeds, execution_date=20240709T232338, start_date=20240709T232339, end_date=20240709T232339
[2024-07-09 23:23:39,900] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-07-09 23:23:39,933] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
