[2024-07-10 13:53:14,635] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: create_layers_in_snowflake.create_seeds manual__2024-07-10T13:53:14.342487+00:00 [queued]>
[2024-07-10 13:53:14,645] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: create_layers_in_snowflake.create_seeds manual__2024-07-10T13:53:14.342487+00:00 [queued]>
[2024-07-10 13:53:14,645] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 13:53:14,646] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-07-10 13:53:14,646] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 13:53:14,661] {taskinstance.py:1377} INFO - Executing <Task(DockerOperator): create_seeds> on 2024-07-10 13:53:14.342487+00:00
[2024-07-10 13:53:14,664] {standard_task_runner.py:52} INFO - Started process 634 to run task
[2024-07-10 13:53:14,668] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_layers_in_snowflake', 'create_seeds', 'manual__2024-07-10T13:53:14.342487+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/create_layers.py', '--cfg-path', '/tmp/tmpnkzq67pc', '--error-file', '/tmp/tmpj6ntip4r']
[2024-07-10 13:53:14,668] {standard_task_runner.py:80} INFO - Job 9: Subtask create_seeds
[2024-07-10 13:53:14,724] {task_command.py:369} INFO - Running <TaskInstance: create_layers_in_snowflake.create_seeds manual__2024-07-10T13:53:14.342487+00:00 [running]> on host bc9f9d1e47b7
[2024-07-10 13:53:14,803] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_layers_in_snowflake
AIRFLOW_CTX_TASK_ID=create_seeds
AIRFLOW_CTX_EXECUTION_DATE=2024-07-10T13:53:14.342487+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-10T13:53:14.342487+00:00
[2024-07-10 13:53:14,828] {docker.py:247} INFO - Starting docker container from image custom_dbt_image
[2024-07-10 13:53:14,958] {docker.py:308} INFO - sh: 1: cd: can't cd to /dbtlearn
[2024-07-10 13:53:15,010] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 387, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 266, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 313, in _run_image_with_mounts
    raise AirflowException(f'Docker container failed: {repr(result)} lines {joined_log_lines}')
airflow.exceptions.AirflowException: Docker container failed: {'StatusCode': 2} lines sh: 1: cd: can't cd to /dbtlearn
[2024-07-10 13:53:15,022] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=create_layers_in_snowflake, task_id=create_seeds, execution_date=20240710T135314, start_date=20240710T135314, end_date=20240710T135315
[2024-07-10 13:53:15,035] {standard_task_runner.py:97} ERROR - Failed to execute job 9 for task create_seeds (Docker container failed: {'StatusCode': 2} lines sh: 1: cd: can't cd to /dbtlearn; 634)
[2024-07-10 13:53:15,052] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-10 13:53:15,117] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
