[2024-07-10 01:05:21,895] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: create_layers_in_snowflake.check_seeds manual__2024-07-10T01:05:20.622024+00:00 [queued]>
[2024-07-10 01:05:21,905] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: create_layers_in_snowflake.check_seeds manual__2024-07-10T01:05:20.622024+00:00 [queued]>
[2024-07-10 01:05:21,905] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 01:05:21,905] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-07-10 01:05:21,906] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 01:05:21,919] {taskinstance.py:1377} INFO - Executing <Task(DockerOperator): check_seeds> on 2024-07-10 01:05:20.622024+00:00
[2024-07-10 01:05:21,923] {standard_task_runner.py:52} INFO - Started process 1819 to run task
[2024-07-10 01:05:21,926] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_layers_in_snowflake', 'check_seeds', 'manual__2024-07-10T01:05:20.622024+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/create_layers.py', '--cfg-path', '/tmp/tmpd7czej0t', '--error-file', '/tmp/tmpn34ka394']
[2024-07-10 01:05:21,927] {standard_task_runner.py:80} INFO - Job 14: Subtask check_seeds
[2024-07-10 01:05:21,985] {task_command.py:369} INFO - Running <TaskInstance: create_layers_in_snowflake.check_seeds manual__2024-07-10T01:05:20.622024+00:00 [running]> on host 9ba3cd856d5b
[2024-07-10 01:05:22,058] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_layers_in_snowflake
AIRFLOW_CTX_TASK_ID=check_seeds
AIRFLOW_CTX_EXECUTION_DATE=2024-07-10T01:05:20.622024+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-10T01:05:20.622024+00:00
[2024-07-10 01:05:22,080] {docker.py:247} INFO - Starting docker container from image custom_dbt_image
[2024-07-10 01:05:22,186] {docker.py:308} INFO - cat: unrecognized option '--config-dir'
Try 'cat --help' for more information.
[2024-07-10 01:05:22,246] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 387, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 266, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 313, in _run_image_with_mounts
    raise AirflowException(f'Docker container failed: {repr(result)} lines {joined_log_lines}')
airflow.exceptions.AirflowException: Docker container failed: {'StatusCode': 1} lines cat: unrecognized option '--config-dir'
Try 'cat --help' for more information.
[2024-07-10 01:05:22,250] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=create_layers_in_snowflake, task_id=check_seeds, execution_date=20240710T010520, start_date=20240710T010521, end_date=20240710T010522
[2024-07-10 01:05:22,261] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task check_seeds (Docker container failed: {'StatusCode': 1} lines cat: unrecognized option '--config-dir'
Try 'cat --help' for more information.; 1819)
[2024-07-10 01:05:22,269] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-10 01:05:22,302] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
